import type { LucideIcon } from "lucide-react";
import {
  Trees,
  PawPrint,
  Landmark,
  Palette,
  UtensilsCrossed,
  Compass,
  CloudSun,
  Aperture,
  Heart,
} from "lucide-react";
import type { ThemeId } from "./puzzleImages";
import { PUZZLE_IMAGES } from "./puzzleImages";

export interface ThemeMeta {
  id: ThemeId;
  name: string;
  description: string;
  thumbnailImageId: number;
  puzzleCount: number;
  unlockCost: number;
}

// Themes ordered by unlock cost for progression.
// Interleaved across categories so players experience variety as they unlock.
export const THEMES: ThemeMeta[] = [
  // Tier 1: Free & very cheap (0-15 stars)
  {
    id: "nature",
    name: "Nature",
    description: "Forests, rivers, and golden landscapes",
    thumbnailImageId: PUZZLE_IMAGES.nature[0].imageId,
    puzzleCount: 5,
    unlockCost: 0,
  },
  {
    id: "animals",
    name: "Animals",
    description: "Adorable creatures from around the world",
    thumbnailImageId: PUZZLE_IMAGES.animals[0].imageId,
    puzzleCount: 5,
    unlockCost: 3,
  },
  {
    id: "forests",
    name: "Forests",
    description: "Dense woods and shaded paths",
    thumbnailImageId: PUZZLE_IMAGES.forests[0].imageId,
    puzzleCount: 5,
    unlockCost: 12,
  },
  {
    id: "sunsets",
    name: "Sunsets",
    description: "Golden hour and twilight skies",
    thumbnailImageId: PUZZLE_IMAGES.sunsets[0].imageId,
    puzzleCount: 5,
    unlockCost: 16,
  },
  // Tier 2: Early progression (20-50 stars)
  {
    id: "landmarks",
    name: "Landmarks",
    description: "Iconic structures and city views",
    thumbnailImageId: PUZZLE_IMAGES.landmarks[0].imageId,
    puzzleCount: 5,
    unlockCost: 20,
  },
  {
    id: "coffee",
    name: "Coffee",
    description: "Cozy cafes and morning brews",
    thumbnailImageId: PUZZLE_IMAGES.coffee[0].imageId,
    puzzleCount: 5,
    unlockCost: 24,
  },
  {
    id: "lakes",
    name: "Lakes",
    description: "Calm reflections and still waters",
    thumbnailImageId: PUZZLE_IMAGES.lakes[0].imageId,
    puzzleCount: 5,
    unlockCost: 28,
  },
  {
    id: "pets",
    name: "Pets",
    description: "Furry friends and loyal companions",
    thumbnailImageId: PUZZLE_IMAGES.pets[0].imageId,
    puzzleCount: 5,
    unlockCost: 32,
  },
  {
    id: "vintage",
    name: "Vintage",
    description: "Retro cameras and classic cars",
    thumbnailImageId: PUZZLE_IMAGES.vintage[0].imageId,
    puzzleCount: 5,
    unlockCost: 35,
  },
  {
    id: "spring",
    name: "Spring",
    description: "Cherry blossoms and new growth",
    thumbnailImageId: PUZZLE_IMAGES.spring[0].imageId,
    puzzleCount: 5,
    unlockCost: 39,
  },
  {
    id: "coastal",
    name: "Coastal",
    description: "Cliff walks and rocky shorelines",
    thumbnailImageId: PUZZLE_IMAGES.coastal[0].imageId,
    puzzleCount: 5,
    unlockCost: 43,
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Clean lines and negative space",
    thumbnailImageId: PUZZLE_IMAGES.minimalist[0].imageId,
    puzzleCount: 5,
    unlockCost: 47,
  },
  // Tier 3: Mid progression (50-100 stars)
  {
    id: "meadows",
    name: "Meadows",
    description: "Wildflowers and open plains",
    thumbnailImageId: PUZZLE_IMAGES.meadows[0].imageId,
    puzzleCount: 5,
    unlockCost: 52,
  },
  {
    id: "birds",
    name: "Birds",
    description: "Feathered friends in flight",
    thumbnailImageId: PUZZLE_IMAGES.birds[0].imageId,
    puzzleCount: 5,
    unlockCost: 57,
  },
  {
    id: "cityscapes",
    name: "Cityscapes",
    description: "Urban skylines and city streets",
    thumbnailImageId: PUZZLE_IMAGES.cityscapes[0].imageId,
    puzzleCount: 5,
    unlockCost: 62,
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Waves, tides, and open water",
    thumbnailImageId: PUZZLE_IMAGES.ocean[0].imageId,
    puzzleCount: 5,
    unlockCost: 67,
  },
  {
    id: "fruits",
    name: "Fruits",
    description: "Fresh harvest and vibrant produce",
    thumbnailImageId: PUZZLE_IMAGES.fruits[0].imageId,
    puzzleCount: 5,
    unlockCost: 72,
  },
  {
    id: "villages",
    name: "Villages",
    description: "Cobblestone streets and quaint towns",
    thumbnailImageId: PUZZLE_IMAGES.villages[0].imageId,
    puzzleCount: 5,
    unlockCost: 77,
  },
  {
    id: "summer",
    name: "Summer",
    description: "Sun-drenched days and golden fields",
    thumbnailImageId: PUZZLE_IMAGES.summer[0].imageId,
    puzzleCount: 5,
    unlockCost: 82,
  },
  {
    id: "music",
    name: "Music",
    description: "Instruments and concert stages",
    thumbnailImageId: PUZZLE_IMAGES.music[0].imageId,
    puzzleCount: 5,
    unlockCost: 87,
  },
  {
    id: "tropical",
    name: "Tropical",
    description: "Palm trees and island paradise",
    thumbnailImageId: PUZZLE_IMAGES.tropical[0].imageId,
    puzzleCount: 5,
    unlockCost: 92,
  },
  {
    id: "abstract",
    name: "Abstract",
    description: "Light trails and artistic blur",
    thumbnailImageId: PUZZLE_IMAGES.abstract[0].imageId,
    puzzleCount: 5,
    unlockCost: 97,
  },
  // Tier 4: Mid-late (100-170 stars)
  {
    id: "bridges",
    name: "Bridges",
    description: "Stone arches and suspension spans",
    thumbnailImageId: PUZZLE_IMAGES.bridges[0].imageId,
    puzzleCount: 5,
    unlockCost: 103,
  },
  {
    id: "patterns",
    name: "Patterns",
    description: "Geometric shapes and natural symmetry",
    thumbnailImageId: PUZZLE_IMAGES.patterns[0].imageId,
    puzzleCount: 5,
    unlockCost: 109,
  },
  {
    id: "wildlife",
    name: "Wildlife",
    description: "Wild creatures in their habitats",
    thumbnailImageId: PUZZLE_IMAGES.wildlife[0].imageId,
    puzzleCount: 5,
    unlockCost: 115,
  },
  {
    id: "mountains",
    name: "Mountains",
    description: "Peaks, ridges, and alpine views",
    thumbnailImageId: PUZZLE_IMAGES.mountains[0].imageId,
    puzzleCount: 5,
    unlockCost: 121,
  },
  {
    id: "roads",
    name: "Roads",
    description: "Open highways and winding paths",
    thumbnailImageId: PUZZLE_IMAGES.roads[0].imageId,
    puzzleCount: 5,
    unlockCost: 127,
  },
  {
    id: "autumn_colors",
    name: "Autumn Colors",
    description: "Fall foliage and harvest gold",
    thumbnailImageId: PUZZLE_IMAGES.autumn_colors[0].imageId,
    puzzleCount: 5,
    unlockCost: 133,
  },
  {
    id: "fashion",
    name: "Fashion",
    description: "Style, fabrics, and accessories",
    thumbnailImageId: PUZZLE_IMAGES.fashion[0].imageId,
    puzzleCount: 5,
    unlockCost: 139,
  },
  {
    id: "architecture",
    name: "Architecture",
    description: "Buildings, domes, and facades",
    thumbnailImageId: PUZZLE_IMAGES.architecture[0].imageId,
    puzzleCount: 5,
    unlockCost: 145,
  },
  {
    id: "macro",
    name: "Macro",
    description: "Tiny worlds in extreme close-up",
    thumbnailImageId: PUZZLE_IMAGES.macro[0].imageId,
    puzzleCount: 5,
    unlockCost: 151,
  },
  {
    id: "canyons",
    name: "Canyons",
    description: "Red rock and desert landscapes",
    thumbnailImageId: PUZZLE_IMAGES.canyons[0].imageId,
    puzzleCount: 5,
    unlockCost: 157,
  },
  {
    id: "objects",
    name: "Objects",
    description: "Still life and everyday items",
    thumbnailImageId: PUZZLE_IMAGES.objects[0].imageId,
    puzzleCount: 5,
    unlockCost: 163,
  },
  // Tier 5: Late progression (170-250 stars)
  {
    id: "camping",
    name: "Camping",
    description: "Campfires and starry nights",
    thumbnailImageId: PUZZLE_IMAGES.camping[0].imageId,
    puzzleCount: 5,
    unlockCost: 170,
  },
  {
    id: "dining",
    name: "Dining",
    description: "Elegant tables and fine cuisine",
    thumbnailImageId: PUZZLE_IMAGES.dining[0].imageId,
    puzzleCount: 5,
    unlockCost: 177,
  },
  {
    id: "marine",
    name: "Marine",
    description: "Ocean depths and coral reefs",
    thumbnailImageId: PUZZLE_IMAGES.marine[0].imageId,
    puzzleCount: 5,
    unlockCost: 184,
  },
  {
    id: "historic",
    name: "Historic",
    description: "Ancient walls and heritage sites",
    thumbnailImageId: PUZZLE_IMAGES.historic[0].imageId,
    puzzleCount: 5,
    unlockCost: 191,
  },
  {
    id: "winter_snow",
    name: "Winter Snow",
    description: "Frost, ice, and snowy trails",
    thumbnailImageId: PUZZLE_IMAGES.winter_snow[0].imageId,
    puzzleCount: 5,
    unlockCost: 198,
  },
  {
    id: "rivers",
    name: "Rivers",
    description: "Rushing water and peaceful streams",
    thumbnailImageId: PUZZLE_IMAGES.rivers[0].imageId,
    puzzleCount: 5,
    unlockCost: 205,
  },
  {
    id: "workspace",
    name: "Workspace",
    description: "Desks, studios, and creative spaces",
    thumbnailImageId: PUZZLE_IMAGES.workspace[0].imageId,
    puzzleCount: 5,
    unlockCost: 212,
  },
  {
    id: "textures",
    name: "Textures",
    description: "Surface details and tactile beauty",
    thumbnailImageId: PUZZLE_IMAGES.textures[0].imageId,
    puzzleCount: 5,
    unlockCost: 219,
  },
  {
    id: "colorful",
    name: "Colorful",
    description: "Neon glows and vivid splashes",
    thumbnailImageId: PUZZLE_IMAGES.colorful[0].imageId,
    puzzleCount: 5,
    unlockCost: 226,
  },
  {
    id: "harbors",
    name: "Harbors",
    description: "Sailboats and waterfront views",
    thumbnailImageId: PUZZLE_IMAGES.harbors[0].imageId,
    puzzleCount: 5,
    unlockCost: 233,
  },
  {
    id: "misty",
    name: "Misty",
    description: "Morning fog and cloud forests",
    thumbnailImageId: PUZZLE_IMAGES.misty[0].imageId,
    puzzleCount: 5,
    unlockCost: 240,
  },
  // Tier 6: Endgame (250+ stars)
  {
    id: "interiors",
    name: "Interiors",
    description: "Grand halls and cozy rooms",
    thumbnailImageId: PUZZLE_IMAGES.interiors[0].imageId,
    puzzleCount: 5,
    unlockCost: 248,
  },
  {
    id: "night_sky",
    name: "Night Sky",
    description: "Stars, galaxies, and moonlit skies",
    thumbnailImageId: PUZZLE_IMAGES.night_sky[0].imageId,
    puzzleCount: 5,
    unlockCost: 256,
  },
  {
    id: "railways",
    name: "Railways",
    description: "Train tracks and old stations",
    thumbnailImageId: PUZZLE_IMAGES.railways[0].imageId,
    puzzleCount: 5,
    unlockCost: 264,
  },
  {
    id: "dark_moody",
    name: "Dark & Moody",
    description: "Shadows, silhouettes, and low light",
    thumbnailImageId: PUZZLE_IMAGES.dark_moody[0].imageId,
    puzzleCount: 5,
    unlockCost: 272,
  },
  {
    id: "towers",
    name: "Towers",
    description: "Spires, minarets, and high rises",
    thumbnailImageId: PUZZLE_IMAGES.towers[0].imageId,
    puzzleCount: 5,
    unlockCost: 280,
  },
  {
    id: "books",
    name: "Books",
    description: "Libraries, shelves, and reading nooks",
    thumbnailImageId: PUZZLE_IMAGES.books[0].imageId,
    puzzleCount: 5,
    unlockCost: 288,
  },
];

export function getThemeMeta(themeId: ThemeId): ThemeMeta | undefined {
  return THEMES.find((t) => t.id === themeId);
}

export type CategoryId = string;

export interface Category {
  id: CategoryId;
  name: string;
  icon: LucideIcon;
  themeIds: ThemeId[];
}

export const CATEGORIES: Category[] = [
  {
    id: "nature",
    name: "Nature & Landscapes",
    icon: Trees,
    themeIds: [
      "nature",
      "forests",
      "sunsets",
      "lakes",
      "meadows",
      "tropical",
      "canyons",
      "rivers",
      "mountains",
      "ocean",
    ],
  },
  {
    id: "animals",
    name: "Animals & Wildlife",
    icon: PawPrint,
    themeIds: ["animals", "pets", "birds", "wildlife", "marine"],
  },
  {
    id: "architecture",
    name: "Architecture & Cities",
    icon: Landmark,
    themeIds: [
      "landmarks",
      "cityscapes",
      "bridges",
      "architecture",
      "historic",
      "interiors",
      "towers",
    ],
  },
  {
    id: "art",
    name: "Art & Design",
    icon: Palette,
    themeIds: ["vintage", "patterns", "objects", "colorful"],
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: UtensilsCrossed,
    themeIds: ["coffee", "fruits", "dining"],
  },
  {
    id: "travel",
    name: "Travel & Adventure",
    icon: Compass,
    themeIds: [
      "coastal",
      "villages",
      "roads",
      "camping",
      "harbors",
      "railways",
    ],
  },
  {
    id: "seasons",
    name: "Seasons & Weather",
    icon: CloudSun,
    themeIds: [
      "spring",
      "summer",
      "autumn_colors",
      "winter_snow",
      "misty",
      "night_sky",
    ],
  },
  {
    id: "abstract",
    name: "Abstract & Creative",
    icon: Aperture,
    themeIds: ["minimalist", "abstract", "macro", "textures", "dark_moody"],
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    icon: Heart,
    themeIds: ["music", "fashion", "workspace", "books"],
  },
];
