/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ThemeId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserImage = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PuzzleResult = IDL.Record({
  'bestTime' : IDL.Nat,
  'stars' : IDL.Nat,
});
export const ThemeData = IDL.Record({
  'puzzleResults' : IDL.Vec(PuzzleResult),
});
export const UserProgress = IDL.Record({
  'hints' : IDL.Nat,
  'coins' : IDL.Nat,
  'achievements' : IDL.Vec(IDL.Text),
  'themeProgress' : IDL.Vec(IDL.Tuple(ThemeId, ThemeData)),
  'lastHintRegenTime' : IDL.Int,
  'lastDailyDay' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'buyHint' : IDL.Func([], [], []),
  'completeDailyPuzzle' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat, IDL.Nat],
      [],
    ),
  'completePuzzle' : IDL.Func(
      [ThemeId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
      [],
    ),
  'deleteImage' : IDL.Func([IDL.Nat], [], []),
  'getMyImages' : IDL.Func([], [IDL.Vec(UserImage)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProgress' : IDL.Func([], [UserProgress], ['query']),
  'renameImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'startPuzzle' : IDL.Func([ThemeId, IDL.Nat, IDL.Nat], [], []),
  'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [UserImage], []),
  'useHint' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ThemeId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserImage = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PuzzleResult = IDL.Record({ 'bestTime' : IDL.Nat, 'stars' : IDL.Nat });
  const ThemeData = IDL.Record({ 'puzzleResults' : IDL.Vec(PuzzleResult) });
  const UserProgress = IDL.Record({
    'hints' : IDL.Nat,
    'coins' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
    'themeProgress' : IDL.Vec(IDL.Tuple(ThemeId, ThemeData)),
    'lastHintRegenTime' : IDL.Int,
    'lastDailyDay' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'buyHint' : IDL.Func([], [], []),
    'completeDailyPuzzle' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat, IDL.Nat],
        [],
      ),
    'completePuzzle' : IDL.Func(
        [ThemeId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
        [],
      ),
    'deleteImage' : IDL.Func([IDL.Nat], [], []),
    'getMyImages' : IDL.Func([], [IDL.Vec(UserImage)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProgress' : IDL.Func([], [UserProgress], ['query']),
    'renameImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'startPuzzle' : IDL.Func([ThemeId, IDL.Nat, IDL.Nat], [], []),
    'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [UserImage], []),
    'useHint' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };