/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PuzzleResult { 'bestTime' : bigint, 'stars' : bigint }
export interface ThemeData { 'puzzleResults' : Array<PuzzleResult> }
export type ThemeId = string;
export interface UserImage {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : bigint,
}
export interface UserProfile { 'name' : string }
export interface UserProgress {
  'hints' : bigint,
  'coins' : bigint,
  'achievements' : Array<string>,
  'themeProgress' : Array<[ThemeId, ThemeData]>,
  'lastHintRegenTime' : bigint,
  'lastDailyDay' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'buyHint' : ActorMethod<[], undefined>,
  'completeDailyPuzzle' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    [bigint, bigint]
  >,
  'completePuzzle' : ActorMethod<
    [ThemeId, bigint, bigint, bigint, bigint, bigint, boolean],
    [bigint, bigint, boolean, Array<string>]
  >,
  'deleteImage' : ActorMethod<[bigint], undefined>,
  'getMyImages' : ActorMethod<[], Array<UserImage>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProgress' : ActorMethod<[], UserProgress>,
  'renameImage' : ActorMethod<[bigint, string], undefined>,
  'setProfile' : ActorMethod<[string], undefined>,
  'startPuzzle' : ActorMethod<[ThemeId, bigint, bigint], undefined>,
  'uploadImage' : ActorMethod<[string, ExternalBlob], UserImage>,
  'useHint' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];